# Generated by Django 2.2.1 on 2019-05-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('abstract', models.TextField()),
                ('content', models.TextField()),
                ('publishData', models.DateField(auto_now=True)),
            ],
        ),
    ]
